# For Linux environment
pipeline {
    agent any
    stages {
        stage('testing pipeline'){
          steps{
	    echo 'test-1'
            sh 'mkdir from-jenkins'
            sh 'touch from-jenkins/test.txt'
         }
      }
    }
}
